### ISSUE TITLE
Alway error

### ISSUE THREAD

**Issue by dinhhieuac** [aimkiray/auto-metamask#1]
Exception has occurred: TimeoutException
Message: 
  File "/xxxx/xxxxx/Desktop/AutoMetamask.py", line 32, in <module>
    driver = setupWebdriver(metamask_path)
selenium.common.exceptions.TimeoutException: Message:

**Comment by aimkiray** [comment]
Please ensure that you can access GitHub, as the MetaMask extension is downloaded from GitHub releases.

**Comment by aimkiray** [comment]
Alternatively, you can try the new version 0.2.0.
