### ISSUE TITLE
metamask-chrome-10.34.0 not working anymore

### ISSUE THREAD

**Issue by bingowrt** [aimkiray/auto-metamask#3]
it was okay yesterday

but today
it took forever to load then 
shows this 
'MetaMask had trouble starting. This error could be intermittent, so try restarting the extension.

Restart MetaMask
Still getting this message? [Send us a bug report.](https://support.metamask.io/)'

**Comment by bingowrt** [comment]
should i just downgrade chrome?

**Comment by aimkiray** [comment]
If you encounter this error after upgrading Chrome, you might consider downgrading Chrome. Alternatively, try updating the version of Metamask, such as 10.34.x.

**Comment by aimkiray** [comment]
Sometimes this error can be caused by an incorrect RPC node. You can try changing it.
