### ISSUE TITLE
headless mode not working

### ISSUE THREAD

**Issue by bingowrt** [aimkiray/auto-metamask#6]
try to add 
    options.add_argument("--window-size=1440,900")
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    options.add_argument("--headless")
    options.add_argument("--disable-gpu")

in def setupWebdriver(metamask_path, chrome_path=None, version=None, chromedriver_path=None):

--headless mode will take forever to load

**Comment by aimkiray** [comment]
Chrome browser may not be able to use extensions in headless mode. If you want to run on a Linux server, the simplest way is to use Xvfb (virtual display).

**Comment by bingowrt** [comment]
@aimkiray thanks a lot, I will look into that.
